-- テーブルの新規作成

-- ホロメン
-- ゲームリリース時点で収録されているホロメン
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES ( 1, '0期生'   , 'ときのそら', NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES ( 2, '0期生'   , 'ロボ子さん', NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES ( 3, '0期生'   , 'AZKi'      , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES ( 4, '0期生'   , 'みこ'      , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES ( 5, '0期生'   , 'すいせい'  , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES ( 6, '1期生'   , 'アキ'      , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES ( 7, '1期生'   , 'はあと'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES ( 8, '1期生'   , 'フブキ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES ( 9, '1期生'   , 'まつり'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (10, '2期生'   , 'あやめ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (11, '2期生'   , 'ちょこ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (12, '2期生'   , 'スバル'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (13, 'ゲマズ'  , 'ミオ'      , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (14, 'ゲマズ'  , 'おかゆ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (15, 'ゲマズ'  , 'ころね'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (16, '3期生'   , 'ぺこら'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (17, '3期生'   , 'フレア'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (18, '3期生'   , 'ノエル'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (19, '3期生'   , 'マリン'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (20, '4期生'   , 'わため'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (21, '4期生'   , 'トワ'      , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (22, '4期生'   , 'ルーナ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (23, '5期生'   , 'ラミィ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (24, '5期生'   , 'ねね'      , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (25, '5期生'   , 'ぼたん'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (26, '5期生'   , 'ポルカ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (27, 'holoX'   , 'ラプラス'  , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (28, 'holoX'   , 'ルイ'      , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (29, 'holoX'   , 'こより'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (30, 'holoX'   , 'いろは'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (31, 'ID 1期生', 'リス'      , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (32, 'ID 1期生', 'ムーナ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (33, 'ID 1期生', 'イオフィ'  , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (34, 'ID 2期生', 'オリー'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (35, 'ID 2期生', 'アーニャ'  , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (36, 'ID 2期生', 'レイネ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (37, 'ID 3期生', 'ゼータ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (38, 'ID 3期生', 'カエラ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (39, 'ID 3期生', 'こぼ'      , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (40, 'Myth'    , 'カリオペ'  , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (41, 'Myth'    , 'キアラ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (42, 'Myth'    , '伊那尓栖'  , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (43, 'Promise' , 'IRyS'      , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (44, 'Promise' , 'クロニー'  , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (45, 'Promise' , 'ベールズ'  , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (46, 'Advent'  , 'シオリ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (47, 'Advent'  , 'ビジュー'  , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (48, 'Advent'  , 'ネリッサ'  , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (49, 'Advent'  , 'フワワ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (50, 'Advent'  , 'モココ'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (51, 'ReGLOSS' , '奏'        , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (52, 'ReGLOSS' , '莉々華'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (53, 'ReGLOSS' , 'らでん'    , NULL, 1);
INSERT INTO holomems (sort_order, group_name, name, note, is_active) VALUES (54, 'ReGLOSS' , 'はじめ'    , NULL, 1);

-- カード
-- ゲームリリース時点で収録されている通常版カード
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 1, 3, '通常版 ときのそら', 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 1, 4, '通常版 ときのそら', 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 1, 5, '通常版 ときのそら', 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 2, 3, '通常版 ロボ子さん', 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 2, 4, '通常版 ロボ子さん', 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 2, 5, '通常版 ロボ子さん', 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 3, 3, '通常版 AZKi'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 3, 4, '通常版 AZKi'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 3, 5, '通常版 AZKi'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 4, 3, '通常版 みこ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 4, 4, '通常版 みこ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 4, 5, '通常版 みこ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 5, 3, '通常版 すいせい'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 5, 4, '通常版 すいせい'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 5, 5, '通常版 すいせい'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 6, 3, '通常版 アキ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 6, 4, '通常版 アキ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 6, 5, '通常版 アキ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 7, 3, '通常版 はあと'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 7, 4, '通常版 はあと'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 7, 5, '通常版 はあと'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 8, 3, '通常版 フブキ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 8, 4, '通常版 フブキ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 8, 5, '通常版 フブキ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 9, 3, '通常版 まつり'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 9, 4, '通常版 まつり'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 9, 5, '通常版 まつり'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (10, 3, '通常版 あやめ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (10, 4, '通常版 あやめ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (10, 5, '通常版 あやめ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (11, 3, '通常版 ちょこ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (11, 4, '通常版 ちょこ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (11, 5, '通常版 ちょこ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (12, 3, '通常版 スバル'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (12, 4, '通常版 スバル'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (12, 5, '通常版 スバル'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (13, 3, '通常版 ミオ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (13, 4, '通常版 ミオ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (13, 5, '通常版 ミオ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (14, 3, '通常版 おかゆ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (14, 4, '通常版 おかゆ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (14, 5, '通常版 おかゆ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (15, 3, '通常版 ころね'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (15, 4, '通常版 ころね'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (15, 5, '通常版 ころね'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (16, 3, '通常版 ぺこら'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (16, 4, '通常版 ぺこら'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (16, 5, '通常版 ぺこら'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (17, 3, '通常版 フレア'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (17, 4, '通常版 フレア'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (17, 5, '通常版 フレア'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (18, 3, '通常版 ノエル'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (18, 4, '通常版 ノエル'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (18, 5, '通常版 ノエル'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (19, 3, '通常版 マリン'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (19, 4, '通常版 マリン'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (19, 5, '通常版 マリン'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (20, 3, '通常版 わため'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (20, 4, '通常版 わため'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (20, 5, '通常版 わため'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (21, 3, '通常版 トワ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (21, 4, '通常版 トワ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (21, 5, '通常版 トワ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (22, 3, '通常版 ルーナ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (22, 4, '通常版 ルーナ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (22, 5, '通常版 ルーナ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (23, 3, '通常版 ラミィ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (23, 4, '通常版 ラミィ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (23, 5, '通常版 ラミィ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (24, 3, '通常版 ねね'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (24, 4, '通常版 ねね'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (24, 5, '通常版 ねね'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (25, 3, '通常版 ぼたん'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (25, 4, '通常版 ぼたん'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (25, 5, '通常版 ぼたん'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (26, 3, '通常版 ポルカ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (26, 4, '通常版 ポルカ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (26, 5, '通常版 ポルカ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (27, 3, '通常版 ラプラス'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (27, 4, '通常版 ラプラス'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (27, 5, '通常版 ラプラス'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (28, 3, '通常版 ルイ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (28, 4, '通常版 ルイ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (28, 5, '通常版 ルイ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (29, 3, '通常版 こより'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (29, 4, '通常版 こより'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (29, 5, '通常版 こより'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (30, 3, '通常版 いろは'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (30, 4, '通常版 いろは'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (30, 5, '通常版 いろは'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (31, 3, '通常版 リス'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (31, 4, '通常版 リス'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (31, 5, '通常版 リス'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (32, 3, '通常版 ムーナ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (32, 4, '通常版 ムーナ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (32, 5, '通常版 ムーナ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (33, 3, '通常版 イオフィ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (33, 4, '通常版 イオフィ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (33, 5, '通常版 イオフィ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (34, 3, '通常版 オリー'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (34, 4, '通常版 オリー'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (34, 5, '通常版 オリー'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (35, 3, '通常版 アーニャ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (35, 4, '通常版 アーニャ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (35, 5, '通常版 アーニャ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (36, 3, '通常版 レイネ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (36, 4, '通常版 レイネ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (36, 5, '通常版 レイネ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (37, 3, '通常版 ゼータ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (37, 4, '通常版 ゼータ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (37, 5, '通常版 ゼータ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (38, 3, '通常版 カエラ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (38, 4, '通常版 カエラ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (38, 5, '通常版 カエラ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (39, 3, '通常版 こぼ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (39, 4, '通常版 こぼ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (39, 5, '通常版 こぼ'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (40, 3, '通常版 カリオペ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (40, 4, '通常版 カリオペ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (40, 5, '通常版 カリオペ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (41, 3, '通常版 キアラ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (41, 4, '通常版 キアラ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (41, 5, '通常版 キアラ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (42, 3, '通常版 伊那尓栖'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (42, 4, '通常版 伊那尓栖'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (42, 5, '通常版 伊那尓栖'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (43, 3, '通常版 IRyS'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (43, 4, '通常版 IRyS'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (43, 5, '通常版 IRyS'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (44, 3, '通常版 クロニー'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (44, 4, '通常版 クロニー'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (44, 5, '通常版 クロニー'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (45, 3, '通常版 ベールズ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (45, 4, '通常版 ベールズ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (45, 5, '通常版 ベールズ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (46, 3, '通常版 シオリ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (46, 4, '通常版 シオリ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (46, 5, '通常版 シオリ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (47, 3, '通常版 ビジュー'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (47, 4, '通常版 ビジュー'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (47, 5, '通常版 ビジュー'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (48, 3, '通常版 ネリッサ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (48, 4, '通常版 ネリッサ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (48, 5, '通常版 ネリッサ'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (49, 3, '通常版 フワワ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (49, 4, '通常版 フワワ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (49, 5, '通常版 フワワ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (50, 3, '通常版 モココ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (50, 4, '通常版 モココ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (50, 5, '通常版 モココ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (51, 3, '通常版 奏'        , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (51, 4, '通常版 奏'        , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (51, 5, '通常版 奏'        , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (52, 3, '通常版 莉々華'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (52, 4, '通常版 莉々華'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (52, 5, '通常版 莉々華'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (53, 3, '通常版 らでん'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (53, 4, '通常版 らでん'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (53, 5, '通常版 らでん'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (54, 3, '通常版 はじめ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (54, 4, '通常版 はじめ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (54, 5, '通常版 はじめ'    , 0, 1, 0);
-- 現時点で公開されているイベント限定カード
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (12, 5, '2026夏イベ スバル'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (17, 5, '2026夏イベ フレア'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (18, 5, '2026夏イベ ノエル'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (20, 5, '2026夏イベ わため'  , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES (51, 5, '2026夏イベ 奏'      , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 4, 5, '2026夏イベ みこ'    , 0, 1, 0);
INSERT INTO cards (holomems_id, rarity, name, is_owned, level, bloom) VALUES ( 5, 5, '2026夏イベ すいせい', 0, 1, 0);

-- ホロワーク達成状況
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES ( 1, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES ( 2, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES ( 3, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES ( 4, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES ( 5, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES ( 6, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES ( 7, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES ( 8, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES ( 9, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (10, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (11, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (12, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (13, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (14, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (15, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (16, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (17, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (18, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (19, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (20, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (21, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (22, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (23, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (24, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (25, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (26, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (27, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (28, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (29, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (30, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (31, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (32, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (33, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (34, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (35, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (36, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (37, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (38, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (39, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (40, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (41, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (42, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (43, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (44, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (45, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (46, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (47, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (48, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (49, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (50, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (51, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (52, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (53, 0, NULL);
INSERT INTO holowork_achievements (holomems_id, current_count, note) VALUES (54, 0, NULL);

-- ホロワークの枠
INSERT INTO holoworks (name) VALUES ('歌配信'    );
INSERT INTO holoworks (name) VALUES ('ゲーム配信');
INSERT INTO holoworks (name) VALUES ('雑談配信'  );
INSERT INTO holoworks (name) VALUES ('収録'      );

-- 自由メモ : 1レコード入れておく (アプリ側でも対応しているので必須ではない・やらなくても動く)
INSERT INTO memo (content) VALUES (NULL);
